### ISSUE TITLE
Output as stream?

### ISSUE THREAD

**Issue by mwoz123** [grawlinson/quick-epub#5]
First of all thanks for your work.

I've one question: is there a way to return output as stream or any other format (for further processing eg. send to ftp). Insteam of directly writing file to a disk. Cause maybe I overlooked it?

**Comment by grawlinson** [comment]
I've been wanting to implement something like that for a while, but have always been busy.

I quickly had a look at [streampub](https://www.npmjs.com/package/streampub) and it *may* do what you want. I'll leave this open, as it's a good issue.

Thanks! 👍
